// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectVG.Infrastructure.Data;

#nullable disable

namespace ProjectVG.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectVGDbContext))]
    [Migration("20250724145413_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectVG.Domain.Entities.Character.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SpeechStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Background = "",
                            CreatedAt = new DateTime(2025, 7, 24, 14, 54, 13, 93, DateTimeKind.Utc).AddTicks(3060),
                            Description = "20대 대학생 여사친 느낌의 귀엽고 발랄한 AI 캐릭터",
                            IsActive = true,
                            Metadata = "{}",
                            Name = "하루",
                            Personality = "장난기 많고 친근하며 감정 표현이 풍부함",
                            Role = "여사친 또는 여친 같은 존재",
                            SpeechStyle = "",
                            UpdatedAt = new DateTime(2025, 7, 24, 14, 54, 13, 93, DateTimeKind.Utc).AddTicks(3060),
                            VoiceId = "haru"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Background = "",
                            CreatedAt = new DateTime(2025, 7, 24, 14, 54, 13, 93, DateTimeKind.Utc).AddTicks(3063),
                            Description = "게임 속 조력자 같은 꼬마 마법사 느낌의 AI 캐릭터",
                            IsActive = true,
                            Metadata = "{}",
                            Name = "미야",
                            Personality = "조금 새침하고 똑똑하며, 호기심이 많고 귀여움",
                            Role = "어린 조력자",
                            SpeechStyle = "",
                            UpdatedAt = new DateTime(2025, 7, 24, 14, 54, 13, 93, DateTimeKind.Utc).AddTicks(3063),
                            VoiceId = "miya"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Background = "",
                            CreatedAt = new DateTime(2025, 7, 24, 14, 54, 13, 93, DateTimeKind.Utc).AddTicks(3065),
                            Description = "조용하고 나긋나긋한 말투의 메이드 느낌 AI 캐릭터",
                            IsActive = true,
                            Metadata = "{}",
                            Name = "소피아",
                            Personality = "차분하고 배려심 깊으며 살짝 순종적",
                            Role = "헌신적인 메이드",
                            SpeechStyle = "",
                            UpdatedAt = new DateTime(2025, 7, 24, 14, 54, 13, 93, DateTimeKind.Utc).AddTicks(3065),
                            VoiceId = "sophia"
                        });
                });

            modelBuilder.Entity("ProjectVG.Domain.Entities.ConversationHistory.ConversationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CharacterId", "Timestamp");

                    b.ToTable("ConversationHistories");
                });

            modelBuilder.Entity("ProjectVG.Domain.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProviderId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 7, 24, 14, 54, 13, 93, DateTimeKind.Utc).AddTicks(3082),
                            Email = "test@test.com",
                            IsActive = true,
                            Name = "Test User",
                            Provider = "test",
                            ProviderId = "test",
                            UpdatedAt = new DateTime(2025, 7, 24, 14, 54, 13, 93, DateTimeKind.Utc).AddTicks(3082),
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("ProjectVG.Domain.Entities.ConversationHistory.ConversationHistory", b =>
                {
                    b.HasOne("ProjectVG.Domain.Entities.Character.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectVG.Domain.Entities.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
